### ISSUE TITLE
Update/remove deprecated packages in `@microsoft/vscode-azext-azureutils`

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-azuretools#1178]
The following packages used by `@microsoft/vscode-azext-azureutils` are deprecated and should be updated to >=2.0.0, or removed:

- [ ] `@azure/arm-resources-subscriptions@1.0.1` (#1180)
- [x] `@azure/arm-resources-profile-2020-09-01-hybrid@1.1.1` (#1192)
- [x] `@azure/arm-storage-profile-2020-09-01-hybrid@1.1.1` (#1192)
